/* -------------------------------------------------------------------------------

    Copyright 2000-2006 Adobe Systems Incorporated. All Rights Reserved.

    NOTICE:  Adobe permits you to use, modify, and distribute this file 
    in accordance with the terms of the Adobe license agreement accompanying 
    it. If you have received this file from a source other than Adobe, then 
    your use, modification, or distribution of it requires the prior written 
    permission of Adobe.

 ----------------------------------------------------------------------------------

	File:	ATETextSuitesDeclare.h
		
	Notes:	Machine Generated file from script version 1.45
	        Please don't modify manually!
	
 ---------------------------------------------------------------------------------- */
	DECLARE_ATE_AUTOSUITE(ApplicationPaint)
	DECLARE_ATE_AUTOSUITE(CompFont)
	DECLARE_ATE_AUTOSUITE(CompFontClass)
	DECLARE_ATE_AUTOSUITE(CompFontClassSet)
	DECLARE_ATE_AUTOSUITE(CompFontComponent)
	DECLARE_ATE_AUTOSUITE(CompFontSet)
	DECLARE_ATE_AUTOSUITE(GlyphRun)
	DECLARE_ATE_AUTOSUITE(GlyphRunsIterator)
	DECLARE_ATE_AUTOSUITE(MojiKumi)
	DECLARE_ATE_AUTOSUITE(MojiKumiSet)
	DECLARE_ATE_AUTOSUITE(TextFrame)
	DECLARE_ATE_AUTOSUITE(TextFramesIterator)
	DECLARE_ATE_AUTOSUITE(TextLine)
	DECLARE_ATE_AUTOSUITE(TextLinesIterator)
	DECLARE_ATE_AUTOSUITE(TextResources)
	DECLARE_ATE_AUTOSUITE(ApplicationTextResources)
	DECLARE_ATE_AUTOSUITE(DocumentTextResources)
	DECLARE_ATE_AUTOSUITE(VersionInfo)
	DECLARE_ATE_AUTOSUITE(ArrayApplicationPaintRef)
	DECLARE_ATE_AUTOSUITE(ArrayReal)
	DECLARE_ATE_AUTOSUITE(ArrayBool)
	DECLARE_ATE_AUTOSUITE(ArrayInteger)
	DECLARE_ATE_AUTOSUITE(ArrayLineCapType)
	DECLARE_ATE_AUTOSUITE(ArrayFigureStyle)
	DECLARE_ATE_AUTOSUITE(ArrayLineJoinType)
	DECLARE_ATE_AUTOSUITE(ArrayWariChuJustification)
	DECLARE_ATE_AUTOSUITE(ArrayStyleRunAlignment)
	DECLARE_ATE_AUTOSUITE(ArrayAutoKernType)
	DECLARE_ATE_AUTOSUITE(ArrayBaselineDirection)
	DECLARE_ATE_AUTOSUITE(ArrayLanguage)
	DECLARE_ATE_AUTOSUITE(ArrayFontCapsOption)
	DECLARE_ATE_AUTOSUITE(ArrayFontBaselineOption)
	DECLARE_ATE_AUTOSUITE(ArrayFontOpenTypePositionOption)
	DECLARE_ATE_AUTOSUITE(ArrayUnderlinePosition)
	DECLARE_ATE_AUTOSUITE(ArrayStrikethroughPosition)
	DECLARE_ATE_AUTOSUITE(ArrayParagraphJustification)
	DECLARE_ATE_AUTOSUITE(ArrayArrayReal)
	DECLARE_ATE_AUTOSUITE(ArrayBurasagariType)
	DECLARE_ATE_AUTOSUITE(ArrayPreferredKinsokuOrder)
	DECLARE_ATE_AUTOSUITE(ArrayKinsokuRef)
	DECLARE_ATE_AUTOSUITE(ArrayMojiKumiRef)
	DECLARE_ATE_AUTOSUITE(ArrayMojiKumiSetRef)
	DECLARE_ATE_AUTOSUITE(ArrayTabStopsRef)
	DECLARE_ATE_AUTOSUITE(ArrayLeadingType)
	DECLARE_ATE_AUTOSUITE(ArrayFontRef)
	DECLARE_ATE_AUTOSUITE(ArrayGlyphID)
	DECLARE_ATE_AUTOSUITE(ArrayRealPoint)
	DECLARE_ATE_AUTOSUITE(ArrayRealMatrix)
#if SLO_COMPLEXSCRIPT
	DECLARE_ATE_AUTOSUITE(ArrayParagraphDirection)
	DECLARE_ATE_AUTOSUITE(ArrayJustificationMethod)
	DECLARE_ATE_AUTOSUITE(ArrayKashidaWidth)
	DECLARE_ATE_AUTOSUITE(ArrayKashidas)
	DECLARE_ATE_AUTOSUITE(ArrayDirOverride)
	DECLARE_ATE_AUTOSUITE(ArrayDigitSet)
	DECLARE_ATE_AUTOSUITE(ArrayDiacVPos)
#endif
	DECLARE_ATE_AUTOSUITE(CharFeatures)
	DECLARE_ATE_AUTOSUITE(CharInspector)
	DECLARE_ATE_AUTOSUITE(CharStyle)
	DECLARE_ATE_AUTOSUITE(CharStyles)
	DECLARE_ATE_AUTOSUITE(CharStylesIterator)
	DECLARE_ATE_AUTOSUITE(Find)
	DECLARE_ATE_AUTOSUITE(Font)
	DECLARE_ATE_AUTOSUITE(Glyph)
	DECLARE_ATE_AUTOSUITE(Glyphs)
	DECLARE_ATE_AUTOSUITE(GlyphsIterator)
	DECLARE_ATE_AUTOSUITE(Kinsoku)
	DECLARE_ATE_AUTOSUITE(KinsokuSet)
	DECLARE_ATE_AUTOSUITE(ParaFeatures)
	DECLARE_ATE_AUTOSUITE(Paragraph)
	DECLARE_ATE_AUTOSUITE(ParagraphsIterator)
	DECLARE_ATE_AUTOSUITE(ParaInspector)
	DECLARE_ATE_AUTOSUITE(ParaStyle)
	DECLARE_ATE_AUTOSUITE(ParaStyles)
	DECLARE_ATE_AUTOSUITE(ParaStylesIterator)
	DECLARE_ATE_AUTOSUITE(Spell)
	DECLARE_ATE_AUTOSUITE(Stories)
	DECLARE_ATE_AUTOSUITE(Story)
	DECLARE_ATE_AUTOSUITE(TabStop)
	DECLARE_ATE_AUTOSUITE(TabStops)
	DECLARE_ATE_AUTOSUITE(TabStopsIterator)
	DECLARE_ATE_AUTOSUITE(TextRange)
	DECLARE_ATE_AUTOSUITE(TextRanges)
	DECLARE_ATE_AUTOSUITE(TextRangesIterator)
	DECLARE_ATE_AUTOSUITE(TextRunsIterator)
	DECLARE_ATE_AUTOSUITE(WordsIterator)
	DECLARE_ATE_AUTOSUITE(ArrayLine)
	DECLARE_ATE_AUTOSUITE(ArrayComposerEngine)