<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="NUnit" Version="3.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RhinoInside\RhinoInside.csproj" />
    <ProjectReference Include="..\RhinoInside.TestClient\RhinoInside.TestClient.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$(RhinoAPIVersion.StartsWith('8'))">
    <PackageReference Include="RhinoCommon" Version="8.0.23304.9001" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup Condition="$(RhinoAPIVersion.StartsWith('7'))">
    <PackageReference Include="RhinoCommon" Version="7.*" IncludeAssets="build;compile" />
  </ItemGroup>
</Project>
