<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>rhinoinside-testclient</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RhinoInside\RhinoInside.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$(RhinoAPIVersion.StartsWith('9'))">
    <PackageReference Include="RhinoCommon" Version="9.0.25051.305-wip" ExcludeAssets="runtime" />
    <PackageReference Include="Grasshopper" Version="9.0.25051.305-wip" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup Condition="$(RhinoAPIVersion.StartsWith('8'))">
    <PackageReference Include="RhinoCommon" Version="8.0.23304.9001" ExcludeAssets="runtime" />
    <PackageReference Include="Grasshopper" Version="8.0.23304.9001" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup Condition="$(RhinoAPIVersion.StartsWith('7'))">
    <PackageReference Include="RhinoCommon" Version="7.*" IncludeAssets="build;compile" />
  </ItemGroup>
</Project>
