<?xml version="1.0" encoding="UTF-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0;net8.0-windows;net9.0;net9.0-windows</TargetFrameworks>
    <LangVersion>10</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <RhinoInsideVersion>9.0.0</RhinoInsideVersion>
    <RhinoAPIVersion>9.0.25051.305-wip</RhinoAPIVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <PropertyGroup Condition="$(TargetFramework.EndsWith('windows'))">
    <UseWpf>true</UseWpf>
    <UseWinForms>true</UseWinForms>
  </PropertyGroup>
</Project>
