<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net7.0;net7.0-windows;</TargetFrameworks>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <RunAnalyzersDuringBuild>True</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>True</RunAnalyzersDuringLiveAnalysis>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <LangVersion>10</LangVersion>
  </PropertyGroup>

  <!-- for Rhino>=8 in dotnet core -->
  <PropertyGroup Condition="!$(TargetFramework.StartsWith('net4'))">
    <RhinoAPIVersion>8.*</RhinoAPIVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <!-- for Rhino>=7 in dotnet framework -->
  <PropertyGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <RhinoAPIVersion>7.*</RhinoAPIVersion>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <!-- nuget properties -->
  <PropertyGroup>
    <PackageId>Rhino.Inside</PackageId>
    <RootNamespace>Rhino.Inside</RootNamespace>
    <AssemblyName>Rhino.Inside</AssemblyName>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Product>Rhino.Inside</Product>
    <Version>8.0.0</Version>
    <PackageVersion>$(Version)</PackageVersion>
    <Title>Rhino.Inside Assembly Resolver</Title>
    <Description>Rhino.Inside assembly resolver for Rhino3D</Description>
    <Authors>Robert McNeel and Associates</Authors>
    <Company>McNeel</Company>
    <Copyright>Copyright (c) 1997-2024 Robert McNeel and Associates</Copyright>
    <RepositoryUrl>https://github.com/mcneel/Rhino.Inside.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>Rhino Rhino3D Rhino.Inside</PackageTags>
    <PackageProjectUrl>https://github.com/mcneel/Rhino.Inside</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReleaseNotes>https://github.com/mcneel/Rhino.Inside/blob/main/CHANGELOG.md</PackageReleaseNotes>
    <!-- <PackageIcon>icon.png</PackageIcon> -->
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <!-- embedded stuff for NuGet -->
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\..\README.md" Pack="true" PackagePath="" />
    <!-- <None Include="$(MSBuildThisFileDirectory)..\..\art\icon.png" Pack="true" PackagePath="" /> -->
  </ItemGroup>

  <PropertyGroup Condition="$(TargetFramework.EndsWith('windows'))">
    <UseWpf>true</UseWpf>
    <UseWinForms>true</UseWinForms>
  </PropertyGroup>

  <ItemGroup Condition="$(RhinoAPIVersion.StartsWith('8'))">
    <Compile Remove="Resolver.cs" />
    <PackageReference Include="RhinoCommon" Version="8.0.23304.9001" ExcludeAssets="runtime" />
    <PackageReference Include="Grasshopper" Version="8.0.23304.9001" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup Condition="$(RhinoAPIVersion.StartsWith('7'))">
    <Compile Remove="*.cs" />
    <Compile Include="Resolver.cs" />
    <PackageReference Include="RhinoCommon" Version="7.0.20314.3001" ExcludeAssets="runtime" />
    <PackageReference Include="Grasshopper" Version="7.0.20314.3001" ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
