<Project Sdk="Microsoft.NET.Sdk">
  <!-- Include all builds in the nuget package for all platforms -->
  <PropertyGroup>
    <TargetFrameworks>net48;net7.0;net7.0-windows</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <RunAnalyzersDuringBuild>True</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>True</RunAnalyzersDuringLiveAnalysis>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <NoWarn>IDE0130</NoWarn>
  </PropertyGroup>

  <!-- nuget properties -->
  <PropertyGroup>
    <PackageId>Rhino.Inside</PackageId>
    <RootNamespace>Rhino.Inside</RootNamespace>
    <AssemblyName>Rhino.Inside</AssemblyName>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Product>Rhino.Inside</Product>
    <Version>8.0.4</Version>
    <PackageVersion>$(Version)-beta</PackageVersion>
    <Title>Rhino.Inside Assembly Resolver</Title>
    <Description>Rhino.Inside assembly resolver for Rhino3D</Description>
    <Authors>Robert McNeel and Associates</Authors>
    <Company>McNeel</Company>
    <Copyright>Copyright (c) 1997-2025 Robert McNeel and Associates</Copyright>
    <RepositoryUrl>https://github.com/mcneel/Rhino.Inside.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>Rhino Rhino3D Rhino.Inside</PackageTags>
    <PackageProjectUrl>https://github.com/mcneel/Rhino.Inside</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReleaseNotes>https://github.com/mcneel/Rhino.Inside/blob/main/CHANGELOG.md</PackageReleaseNotes>
    <!-- <PackageIcon>icon.png</PackageIcon> -->
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <!-- embedded stuff for NuGet -->
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\..\README.md" Pack="true" PackagePath="" />
    <!-- <None Include="$(MSBuildThisFileDirectory)..\..\art\icon.png" Pack="true" PackagePath="" /> -->
  </ItemGroup>

  <ItemGroup Condition="$(RhinoAPIVersion.StartsWith('8'))">
    <Compile Remove="Resolver.cs" />
    <PackageReference Include="RhinoCommon" Version="8.0.23304.9001" ExcludeAssets="runtime" />
    <PackageReference Include="Grasshopper" Version="8.0.23304.9001" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup Condition="$(RhinoAPIVersion.StartsWith('7'))">
    <Compile Remove="Resolver_R8.cs" />
    <PackageReference Include="RhinoCommon" Version="7.0.20314.3001" ExcludeAssets="runtime" />
    <PackageReference Include="Grasshopper" Version="7.0.20314.3001" ExcludeAssets="runtime" />
  </ItemGroup>

  <Target Name="CopyPackage" AfterTargets="Pack">
    <Copy SourceFiles="$(OutputPath)\$(PackageId).$(PackageVersion).nupkg" DestinationFolder="..\build" />
  </Target>
</Project>
