<?xml version="1.0" encoding="UTF-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworks>net48;net7.0;net7.0-windows;net8.0;net8.0-windows</TargetFrameworks>
    <LangVersion>10</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <RhinoInsideVersion>8.0.5</RhinoInsideVersion>
    <RhinoAPIVersion>8.0.23304.9001</RhinoAPIVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <CopyrightYear>2025</CopyrightYear>
    <RepositoryUrl>https://github.com/mcneel/Rhino.Inside.git</RepositoryUrl>
    <PackageProjectUrl>https://github.com/mcneel/rhino.inside/tree/rhino-8.x</PackageProjectUrl>
    <PackageReleaseNotes>https://github.com/mcneel/rhino.inside/blob/rhino-8.x/CHANGELOG.md</PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup Condition="$(TargetFramework.EndsWith('windows'))">
    <UseWpf>true</UseWpf>
    <UseWinForms>true</UseWinForms>
  </PropertyGroup>
</Project>
