#!/bin/bash
# ensure rhino system path is provided
# C:/Program Files/Rhino 8/System on Windows
# /Application/Rhino 8.app/Contents/Frameworks on macOS
if [ -z "$1" ]; then
  echo "Usage: $0 <rhino_system_path>"
  exit 1
fi
export RHINOINSIDE_RHINOPATH=$1
export DYLD_LIBRARY_PATH=$RHINOINSIDE_RHINOPATH/Contents/Frameworks
echo "DYLD_LIBRARY_PATH =     "$DYLD_LIBRARY_PATH
echo "RHINOINSIDE_RHINOPATH = "$RHINOINSIDE_RHINOPATH
dotnet clean RhinoInside.sln
dotnet test RhinoInside.sln /tl:off -v:normal --framework net9.0 -e RHINOINSIDE_RHINOPATH=$1
export -n DYLD_LIBRARY_PATH
export -n RHINOINSIDE_RHINOPATH
