#pragma once

/*
*        Name:	AIPluginNames.h
*        Date:	Feb 14, 1997
*
* ADOBE SYSTEMS INCORPORATED
* Copyright 1986-2016 Adobe Systems Incorporated.
* All rights reserved.
*
* NOTICE:  Adobe permits you to use, modify, and distribute this file
* in accordance with the terms of the Adobe license agreement
* accompanying it. If you have received this file from a source other
* than Adobe, then your use, modification, or distribution of it
* requires the prior written permission of Adobe.
*
* Includes names for all plugins
*
*/


#define kAIAppPluginName						"Adobe AI Application Plugin"


#define k3DPluginName							"3D v2"
#define kAboutPluginsPluginName					"Adobe Illustrator About Plug-ins"
#define kActionManagerPluginName				"AdobeActionManager"
#define kActionPalettePluginName				"AdobeActionPalette"
#define kActionPalettePluginNameEx				"ActionPalette for API Context"
#define kAddAnchorPointsPluginName				"Add Anchor Points"
#define kAddArrowHeadsPluginName				"AddArrowHeads v3"
#define kAdjustColorsPluginName					"Adjust"
#define kAdobeOnlinePluginName					"AdobeOnline"
#define kAdvancedSelectPluginName				"Advanced Select"
#define kAltGyphPalettePluginName				"Alternate Glyph Palette"
#define kAPIUnitTestPluginName					"API Unit Test Plugin"
#define kAppBarControlsPluginName				"Adobe App Bar Controls Host"
#define kArtConvertersPluginName				"Art Converters v2"
#define kArtOnPathBrushPluginName				"AdobeArtBrushTool"
#define kAlignPalettePluginName					"AdobeAlignObjects"
#define kArtStylePluginName					"Adobe Art Style Plugin"
#define kAssetManagementPluginName				"Asset Management"
#define kAssetManagementUIPluginName			"Asset ManagementUI"
#define kAIAATPluginName						"AAT for AI"
#define kAttributesPalettePluginName				kAIAppPluginName
#define kBeautifulStrokesPluginName				"BeautifulStrokes Suite"
#define kBoundingBoxPluginName					"BoundingBox"
#define kBrushManagerPluginName					"AdobeBrushMgr"
#define kCalligraphicBrushPluginName				"Adobe Calligraphic Brush Tool"
#define kCharParaStylesPluginName				"Character and Paragraph Styles"
#define kCharacterPalettePluginName				kAIAppPluginName
#define kCleanupPluginName						"Cleanup"
#define kColorsPluginName						"Colors"
#define kColorHarmonyPluginName					"Adobe Color Harmony Plugin"
#define kControlPalettePluginName				"Control Palette Plugin"
#define kCropPluginName							"Adobe Crop Tool"
#define kCSSExtractPluginName					"CSSExtract"
#define kCSSExtractUIPluginName					"CSSExtractUI"
#define kCurvatureToolPluginName				"Adobe Curvature Tool"
#define kCurvatureToolUIPluginName				"Adobe Curvature ToolUI"
#define kDBrushBrushPluginName					"Adobe dBrush Brush Tool"
#define kDBrushToolUIPluginName					"Adobe dBrush Brush Tool UI"
#define kDeformPluginName						"Adobe Deform Plugin"
#define kDiffusionRasterPluginName				"AdobeDiffusionRaster"
#define kDistortPluginName						"Distort v2"
#define kDocInfoPluginName						"DocInfo"
#define kDocWindowPluginName					"Document Window Plugin"
#define kExperimentationName					"Experimentation Plugin"
#define kHelloPluginName						"Hello Experience Plugin"
#define kAdobeSymbolModelPluginName				"Adobe Symbol Model Plugin"
#define kToolPenPluginName						"Pen Tool Plugin"
#define kDropShadowPluginName					"DropShadow"
#define kDXFDWGFormatPluginName					"Adobe DXFDWG Format"
#define kEraserPluginName						"Adobe Eraser Tool"
#define kEurekaPluginName						"AdobeEurekaPlugin"
#define kExpandPluginName						"Expand"
#define kExpandSuitePluginName					"ExpandS"
#define kEyeBucketPluginName					"AdobeTextDropper"
#define kFileClipboardPrefPluginName				"FileClipboardPreference"
#define kFindPluginName						"Find"
#define kFindReplaceUIPluginName				"Find Replace UI"
#define kFlarePluginName						"Adobe Flare Plugin"
#define kFlatteningPreviewPluginName				"Flattening Preview"
#define kFlattenSuitePluginName					"Flatten Suite"
#define kFlattenTransparencyPluginName			"FlattenTransparency"
#define kFOConversionSuitePluginName				"FO Conversion Suite"
#define kFrameworkSuitePluginName				"FrameworkS"
#define kFuzzyEffectPluginName					"FuzzyEffect v2"
#define kGeometrySuitePluginName				"Adobe Geometry Suite"
#define kGIF89PluginName						"GIF89a Plugin"
#define kGradientMeshPluginName					"GradientMeshPlugin"	// SmoothShade
#define kInfoPalettePluginName					kAIAppPluginName
#define kInversePluginName						"Inverse"
#define kJPEGPluginName						"JPEG Plugin"
#define kJPEG2KPluginName						"JPEG2K Plugin"
#define kKeyboardShortcutsPluginName				"KBSC Plugin"
#define kKinsokuDlgPluginName					"Kinsoku Dlg"
#define kKnifeToolPluginName					"Knife Tool"
#define kLassoPluginName						"Lasso"
#define kLayersPalettePluginName				"AdobeLayerPalette"
#define kLinkPalettePluginName					"AdobeLinkPalette"
#define kLiquifyPluginName						"Liquify"
#define kLiveBlendsPluginName					"Adobe Path Blends"
#define kMagicWandPluginName					"Magic Wand"
#define kMaskHelperPluginName					"MaskHelper v2"
#define kMojikumiPluginName					"Mojikumi UI"
#define kMPSCommonPluginName					"MPSCommon"
#define kMPSExportPluginName					"MPSExport"
#define kMPSParserPluginName					"MPSParser"
#define kFXGFileFormatPluginName				"FXG"
#define kFXGFileFormatUIPluginName				"FXG UI"
#define kNavigatorPalettePluginName				"AdobeNavigator"
#define kObjectMosaicPluginName					"AI Object Mosaic Plug-in"
#define kObjectMosaicUIPluginName				"ObjectMosaicUI"
#define kOffsetPathPluginName					"OffsetPath v2"
#define kOffsetPathUIPluginName					"OffsetPath UI Plugin"
#define kOSExpressViewsPluginName				"OS ExpressViews"
#define kOverprintPluginName					"Overprint"
#define kOverrideCCSuitePluginName				"AIOverrideColorConversionS"
#define kPaintStylePalettesPluginName				"AdobePaintStyle"
#define kParagraphPalettePluginName				kAIAppPluginName
#define kPathfinderPluginName					"AdobePathfinderPalette"
#define kPathfinderSuitePluginName				"Pathfinder Suite"
#define kPathSuitePluginName					"Path Suite"
#define kPDFFormatPluginName					"PDF File Format"
#define kPDFFormatUIPluginName					"PDF File Format UI"
#define kPDFSuitePluginName					"PDF Suite"
#define kPenAndInkPluginName					"Pen And Ink plugin"	//No longer used
#define kPhotoshopAdapterPluginName				"Photoshop Plugin Adapter"
#define kPlanarEditPluginName					"Adobe Planar Edit Plugin"
#define kPNGFileFormatPluginName				"PNG File Format"
#define kPrintPluginName						"Print Plugin"
#define kPSDImportPluginName					"Adobe PSD File Import"
#define kPSDImportUIPluginName					"Adobe PSD File Import UI"
#define kPSDExportPluginName					"Adobe PSD File Export"
#define kPSDExportUIPluginName					"Adobe PSD File Export UI"
#define kPunkPluginName						"Punk v2"
#define kRasterizePluginName					"Rasterize Plugin"
#define kRasterize8PluginName					"Rasterize 8"
#define kReshapeToolPluginName					"Reshape Tool"
#define kReshapeToolUIPluginName				"Reshape Tool UI"
#define kGlobAdjToolUIPluginName 				"GlobAdjToolUI"
#define kRoughenPluginName						"Roughen v2"
#define kRoughenUIPluginName					"RoughenUI"
#define kRoundCornersPluginName					"Round v2"
#define kSangamMapperPluginName					"AISangamMapper"
#define kSaturatePluginName					"Saturate"
#define kSaveForWebAIPluginName					"Save4Web"
#define kScatterBrushPluginName					"Adobe Scatter Brush Tool"
#define kScribblePluginName					"Scribble v2"
#define kScribbleFillPluginName					"Adobe Scribble Fill"
#define kScriptingSupportPluginName				"ScriptingSupport"
#define kScriptsMenuPluginName					"Scripts Menu"
#define kSegmentToolsPluginName					"Segment Tools"
#define kSeparationPreviewPluginName				"SeparationPreviewPlugin"
#define kShapeSuitePluginName					"Shape Suite"
#define kShapeEffectPluginName					"ShapeEffects v2"
#define kShapeToolPluginName					"ShapeTool"
#define kSimplifyPluginName					"Simplify"
#define kSlicingPluginName						"AdobeSlicingPlugin"
#define kSlicingUIPluginName					"AdobeSlicingUI"
#define kSnapomaticPluginName					"Snapomatic"
#define kSpellCheckDictionaryPluginName			"Spell Check Dictionary"
#define kSpellCheckUIPluginName					"Spell Check UI"
#define kStrokeOffsetPluginName					"Stroke Offset v2"
#define kSvgFileFormatPluginName				"SvgFileFormat"
#define kSvgFileFormatUIPluginName				"SvgFileFormatUI"
#define kSvgFilterEffectPluginName				"SVG Filter Effect v2"
#define kSWFExportPluginName					"SWFExport"
#define kSWFExportUIPluginName					"SWFExport UI"
#define kSwatchPalettePluginName				"AdobeSwatch_"
#define kSymbolismPluginName					"Adobe Symbolism"	//	particle systems
#define kSymbolPalettePluginName				"Adobe Symbol Palette Plugin"
#define kTextColumnsPluginName					"TxtColumns"
#define kTextExportPluginName					"TextExport"
#define kTextFindPluginName					"TextFind"			//No longer used
#define kTextFindFontPluginName					"TextFindFont"
#define kTextSmartPunctuationPluginName			"Smart Punctuation"
#define kTextSpellPluginName					"TextSpell"			//No longer used
#define kTextWrapDlgPluginName					"TextWrap Dlg"
#define kTextModelNamePluginName				"TextModel"
#define kTIFFFileFormatPluginName				"TIFF File Format"
#define kTIFFFileFormatUIPluginName				"TIFF File Format UI"
#define kToolPalettePluginName					"AdobeBuiltInToolbox"
#define kToolSelectorPluginName					"AdobeToolSelector"
#define kTracingObjectPluginName				"Adobe Tracing Object"
#define kTracingUIPluginName					"Adobe Tracing UI"
#define kTransformPluginName					"Transform v2"
#define kTransformPalettePluginName				"AdobeTransformObjects"
#define kTransparencyPalettePluginName			"AdobeTransparencyEditor"
#define kTrimMarkPluginName					"TrimMark v2"
#define kTwirlToolPluginName					"Twirl v2"
#define kTypeCasePluginName					"TypeCase"
#define kUnitTestingPluginName					"Unit Testing"
#define kUnitTestingSamplePluginName				"Unit Testing Sample"
#define kVariablesPalettePluginName				"Adobe Variables Palette"
#define kWelcomeScreenPluginName				"Adobe Welcome Screen"
#define kWorkspacePluginName					"Adobe Custom Workspace"
#define kZigZagPluginName						"ZigZag v2"
#define kZigZagUIPluginName					"ZigZagUI"
#define kServicesPluginName					"Services"
#define kNudgePluginName						"Adobe Nudge"
#define kAIBottlenecksPluginName				"AI Bottlenecks Plugin"
#define kPerspectivePluginName					"Adobe Perspective Guides"
#define kPunkUIPluginName						"PuckerAndBloatUI"
#define kAIArtOnPathBrushToolUIPluginName			"ArtOnPathBrushToolUI"
#define kUserInterfacePluginName				"Adobe Illustrator User Interface"
#define kBrushManagerUIPluginName				"AdobeBrushMgrUI"
#define kCurveFittingSuitePluginName					"CurveFittingSuite"
#define kSketchingToolsPluginName					"SketchingTools"
#define kPlanetXPUIPluginName					"PlanetXUI"
#define kExpandUIPluginName					"ExpandUI"
#define kDxfDwgUIPluginName					"DxfDwgUI"
#define kPathfinderUIPluginName					"PathfinderUI"
#define kRasterizeUIPluginName					"RasterizeUI"
#define kSelectionUIPluginName					"SelectionUI"
#define kPerspectiveUIPluginName				"PerspectiveUI"
#define kScribbleUIPluginName					"ScribbleUI"
#define kTextExportUIPluginName					"TextExportUI"
#define kDeformUIPluginName					"DeformUI"
#define kSangamFormatsUIPluginName				"SangamFormatsUI"
#define kCleanupUIPluginName					"CleanupUI"
#define kFlashTextPanelPluginName				"FlashTextPanel"
#define kRoundUIPluginName						"RoundUI"
#define kJPEGFormatUIPluginName					"JPEGFormatUI"
#define kArtboardPalettePluginName				"AdobeArtboardPanel"
#define kVariablesPaletteUIPluginName				"VariablesPaletteUI"
#define kLinkPaletteUIPluginName				"LinkPaletteUI"
#define kJPEGFormatUIPluginName                 	"JPEGFormatUI"
#define kSimplifyUIPluginName					"SimplifyUI"
#define kTracingOptionsUIPluginName				"TracingOptionsUI"
#define kParticleSystemUIPluginName				"ParticleSystemUI"
#define	kShapeEffectUIPluginName				"ShapeEffectUI"
#define kTransformUIPluginName					"TransformUI"
#define kFuzzyEffectUIPluginName				"FuzzyEffectUI"
#define kFlareUIPluginName						"FlareUI"
#define kDynamicCornersPluginName				"DynamicCorners"
#define kContextMenuTouchPluginName				"ContextMenuTouch"
#define kPNGExportPluginName					"PNGExport"
#define kJSONFormatPluginName					"JSONFormat"
#define kAIMenuConfiguratorPluginName			"MenuConfigurator"

// Required plug-ins provided by ADM
#define kASDataStreamPluginName					"ASDataStream Plugin"
#define kADMEveParserPluginName					"ADMEveParser Plugin"

#define kAINewSamplePlugin						"AI New Sample Plugin"
#define kSampleUIPluginName					"Sample UI Plugin"
#define kSaturateUIPluginName					"SaturateUI"
#define kFlattenTransparencyUIPluginName			"FlattenTransparencyUI"
#define kTwirlToolUIPluginName					"TwirlToolUI"
#define kIllustratorUIPluginName				"IllustratorUI"
#define kScribbleFillUIPluginName				"ScribbleFillUI"
#define kPreferenceUIPluginName					"AIPreferenceUI"
#define kDropShadowUIPluginName					"DropShadowUI"
#define kDistortUIPluginName					"DistortUI"
#define kVectorizePluginName					"Vectorize"
#define kVectorizeUIPluginName					"VectorizeUI"

#define kLiveBlendsUIPluginName					"LiveBlendsUI"
#define kScatterBrushToolUIPluginName				"ScatterBrushToolUI"
#define kShaperUIPluginName						"ShaperUI"
#define kShaperPluginName						"Shaper"

#define kLiquifyToolUIPluginName				"LiquifyToolUI"
#define kAddArrowUIPluginName					"AddArrowUI"
#define kAIToolBoxUIPluginName					"AI Toolbox UI Plugin"
#define kPSLFilterAdapterPluginName				"PSLFilterAdapter"
#define kPSLFilterAdapterUIPluginName			"PSLFilterAdapterUI"
#define kAIPackagePluginName					"Package"
#define kAILiveShapesPluginName					"Adobe Live Shapes"
#define kAILiveShapesUIPluginName				"Adobe Live Shapes UI"
#define kAITouchStatusBarUIPluginName			"Touch Status Bar UI"
#define kAIInfoGraphicPluginName				"Adobe InfoGraphic"
#define kAIInfoGraphicUIPluginName				"Adobe InfoGrahic UI"
#define kAIDesignLibraryPluginName				"Design Library"
#define kSmartExportPluginName					"SmartExport"
#define kSmartExportUIPluginName				"SmartExportUI"
#define kIdeaFileFormatUIPluginName				"Idea File Format UI"
#define kAIVulcanServicePluginName				"Vulcan Service"
#define kAIShapeCorePluginName					"Shape Core"
#define kAIShapeCoreUIPluginName				"Shape Core UI"
#define kAISymmetryPluginName					"Symmetry"
#define kAISymmetryUIPluginName					"SymmetryUI"
#define kOnBoardingPluginName					"OnBoarding"
#define kAsyncPluginName						"Async"
#define kCustomProgressSuiteName                "Custom Progress Suite"
#define kAIToolPluginName						"AI Tool Plugin"
#define kAIPGFFileFormatPluginName              "Adobe PGF File Format" 
#define kMultiEveDialogUIPluginName             "Adobe Multi Eve Dialog UI"
#define kCropUIPluginName						"Adobe Crop UI"
#define kVectorSculptingUIPluginName			"Adobe Vector Sculpting UI"
#define kVectorSculptingPluginName				"Vector Sculpting"
#define kPropertiesPanelPluginName				"Properties Panel"
#define kTouchBarPluginName						"Adobe Touch Bar"
#define kTorqExtensionPluginName				"Adobe Torq Extension"
#define kRadialDevicePluginName					"Adobe Radial Device"
#define kDiffusionColoringPluginName			"Adobe Diffusion Coloring"
#define kSmartEditPluginName				    "Adobe Smart Edit"
#define kSmartEditUIPluginName					"Adobe Smart Edit UI"
#define kDeepLearningPluginName				"Adobe Deep Learning"
#define kAdobeLicenseManagerPluginName                  "AdobeLicenseManager"

