#ifndef __SLICE_TYPES_H__
#define __SLICE_TYPES_H__

/*
*        Name:	AISliceTypes.h
*     Purpose:	This file contains information related to slices without much overhead.
*
* ADOBE SYSTEMS INCORPORATED
* Copyright 1999-2007 Adobe Systems Incorporated.
* All rights reserved.
*
* NOTICE:  Adobe permits you to use, modify, and distribute this file 
* in accordance with the terms of the Adobe license agreement 
* accompanying it. If you have received this file from a source other 
* than Adobe, then your use, modification, or distribution of it 
* requires the prior written permission of Adobe.
*
*/


#include "ASTypes.h"

#include "AIHeaderBegin.h"

/** @file AISliceTypes.h */

#ifdef __cplusplus
namespace ai {
#endif

	/** Version of ImageReady slices. */
	const ASInt32 kImageReadySlicesVersion = 5;
	/** Version of ImageReady slices. */
	const ASInt32 kImageReadySlicesOriginVersion = 6;

	/** Identifies an invalid slice. */
	const ASInt32 kInvalidSliceID = -1;
	/** Identifies the default slice. */
	const ASInt32 kDefaultSliceID = 0;
	/** Identifies an invalid slice group. */
	const ASInt32 kInvalidSliceGroupID = -1;
	/** Identifies the default slice group. */
	const ASInt32 kDefaultSliceGroupID = 0;
	/** Identifies the first specifically defined slice group. */
	const ASInt32 kFirstUserSliceGroupID = 1;
	/** Identifies the first group with a single slice (unlinked slice). */
	const ASInt32 kFirstUserSliceSoloGroupID = kFirstUserSliceGroupID + 100000;

	/** Minimum slice dimension value. */
	const ASInt32 kMinSliceDim = 1;
	/** Internal */
	const ASInt32 kForceEnumSize = 0x7FFFFFFF;

	/** Identifies how a slice was created.  */
	enum ESliceOrigin {
		/** Created automatically, "autoOrigin" */
		eSliceOrigin_autoGenerated,
		/** Created as part of layer creation, "layerOrigin" */
		eSliceOrigin_layerGenerated,
		/** Created by the user, "userOrigin" */
		eSliceOrigin_userGenerated,
		/** Internal */
		eSliceOrigin_Unknown = kForceEnumSize
		};

	/** Identifies the type of a slice; see \c #ASSliceSettings. */
	enum ESliceType {
		/** "noImageType" */
		eSliceType_NoImage,
		/** "imageType" */
		eSliceType_Image,
		/** "rollovertType" */
		eSliceType_Rollover,
		/** "likedType" */
		eSliceType_LinkedText,
		eSliceType_Unknown = kForceEnumSize
		};

	/** Horizontal alignment types for slices; see \c #ASSliceSettings. */
	enum ESliceHorzAlign {
		/** Default, "defaultHAlign" */
		eSliceHorzAlign_Default = 0,
		/** Left, "leftHAlign" */
		eSliceHorzAlign_Left,
		/** Center, "centerHAlign" */
		eSliceHorzAlign_Center,
		/** Right, "rightHAlign" */
		eSliceHorzAlign_Right,
		/** Internal */
		eSliceHorzAlign_Unknown = kForceEnumSize
		};

	/** Vertical alignment types for slices; see \c #ASSliceSettings.  */
	enum ESliceVertAlign {
		/** Default, "defaultVAlign" */
		eSliceVertAlign_Default = 0,
		/** Top, "topVAlign" */
		eSliceVertAlign_Top,
		/** Middle, "middleVAlign" */
		eSliceVertAlign_Middle,
		/** Bottom, "bottomVAlign" */
		eSliceVertAlign_Bottom,
		/** Baseline, "baselineVAlign" */
		eSliceVertAlign_Baseline,
		/** Internal */
		eSlicevertAlign_Unknown = kForceEnumSize
		};

	/** Background color types for slices; see \c #ASSliceSettings. */
	enum ESliceBGColorType {
		/** Color, "colorBGColor" */
		eSliceBGColorType_Color = 0,
		/** None, "noneBGColor" */
		eSliceBGColorType_None,
		/** Matte, "matteBGColor" */
		eSliceBGColorType_Matte,
		/** Internal */
		eSliceBGColorType_Unknown = kForceEnumSize
		};

#ifdef __cplusplus
	} // namespace
#endif

#include "AIHeaderEnd.h"
#endif
