name: Build
on:
  pull_request:
    branches: [ 'rhino-9.x' ]
  workflow_dispatch:

env:
  RHINO_TOKEN: ${{ secrets.RHINO_TOKEN }}

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Update Version Numbers
        run: ./src/version/version.sh

      - name: Upload versioned files
        uses: actions/upload-artifact@v4
        with:
          name: version-files
          path: |
            src/Directory.Build.props

  build:
    runs-on: windows-latest
    needs: [ version ]
    steps:
      - name: Get token
        if: (github.event_name == 'pull_request')
        id: my-app
        uses: getsentry/action-github-app-token@v3
        with:
          app_id: ${{ secrets.MERGE_DOWN_APP_ID }}
          private_key: ${{ secrets.MERGE_DOWN_APP_PRIVATE_KEY }}

      - name: Enable Auto-Merge
        if: (github.event_name == 'pull_request')
        uses: kenhowardpdx/auto-merge-action@v1
        with:
          token: ${{ steps.my-app.outputs.token }}

      - name: Install dotnet 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Download versioned files
        uses: actions/download-artifact@v4
        with:
          name: version-files
          path: src/

      - name: Build
        run: dotnet build -c Release src/RhinoInside.sln

      - name: Install Rhino
        uses: mcneel/setup-rhino3d@v2
        id: setup_rhino
        with:
          release-version: wip
          email-address: ${{ secrets.EMAIL_ADDRESS }}

      - name: Run Tests (net48)
        shell: pwsh
        working-directory: ./src
        run: ./rhinoinside-tests.ps1 "C:\Program Files\Rhino 9 WIP\System" net48

      - name: Run Tests (net9.0-windows)
        shell: pwsh
        working-directory: ./src
        run: ./rhinoinside-tests.ps1 "C:\Program Files\Rhino 9 WIP\System" net9.0-windows

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rhinoinside-nupkg
          path: src/build/*.nupkg

  publish:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: (github.event_name == 'workflow_dispatch')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: rhinoinside-nupkg

      - name: Push packages to nuget.org
        run: dotnet nuget push '*.nupkg' --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}